# Generated by Django 3.2.6 on 2021-09-11 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('date_of_creation', models.DateTimeField(blank=True, null=True)),
                ('date_of_modification', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crop_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('District_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Crop_Year', models.IntegerField(blank=True, null=True)),
                ('Season', models.CharField(blank=True, max_length=20, null=True)),
                ('Crop', models.CharField(blank=True, max_length=20, null=True)),
                ('Area', models.IntegerField(blank=True, null=True)),
                ('Production', models.IntegerField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_of_modification', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crops_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropsname', models.CharField(max_length=30)),
                ('crops_description', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
